export default [
  { id: "9", name: "Cálcio", unit: "mg", field: "calcium" },
  { id: "6", name: "Carboidrato", unit: "g", field: "carbohydrate" },
  { id: "8", name: "Cinzas", unit: "g", field: "ash" },
  { id: "16", name: "Cobre", unit: "mg", field: "copper" },
  { id: "5", name: "Colesterol", unit: "mg", field: "cholesterol" },
  { id: "2", name: "Calorias (energia)", unit: "kcal", field: "energy" },
  { id: "13", name: "Ferro", unit: "mg", field: "iron" },
  {
    id: "7",
    name: "Fibra alimentar",
    unit: "g",
    field: "dietary_fiber",
  },
  { id: "12", name: "Fósforo", unit: "mg", field: "phosphorus" },
  { id: "4", name: "Lipídeos", unit: "g", field: "lipids" },
  { id: "10", name: "Magnésio", unit: "mg", field: "magnesium" },
  { id: "11", name: "Manganês", unit: "mg", field: "manganese" },
  { id: "24", name: "Niacina", unit: "mg", field: "niacin" },
  { id: "23", name: "Piridoxina", unit: "mg", field: "pyridoxine" },
  { id: "15", name: "Potássio", unit: "mg", field: "potassium" },
  { id: "3", name: "Proteína", unit: "g", field: "protein" },
  {
    id: "20",
    name: "RAE (Equivalente de Atividade de Retinol)",
    unit: "mcg",
    field: "era",
  },
  {
    id: "19",
    name: "RE (Equivalente de Retinol)",
    unit: "mcg",
    field: "re",
  },
  { id: "18", name: "Retinol", unit: "mcg", field: "retinol" },
  { id: "22", name: "Riboflavina", unit: "mg", field: "riboflavin" },
  { id: "14", name: "Sódio", unit: "mg", field: "sodium" },
  { id: "21", name: "Tiamina", unit: "mg", field: "thiamin" },
  { id: "1", name: "Umidade", unit: "%", field: "moisture" },
  { id: "25", name: "Vitamina C", unit: "mg", field: "vitamin_c" },
  { id: "17", name: "Zinco", unit: "mg", field: "zinc" },
];
